apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: v33besyes-nodejs 
  janus-idp.io/tekton: v33besyes-nodejs
  backstage.io/kubernetes-id: v33besyes-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v33besyes-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  